kafka:
  brokers: localhost:29092
  topic: transactions2

simulation:
  seed: 42
  start-date: "2020-1-1"
  stop-date: "2020-12-31"
  min-daily-customer-count: 1100
  max-daily-customer-count: 1150
  weekend-customer-increase: 50
  price-multiplier: 1.07
  max-items-per-customer: 90
  number-of-unique-customers: 8000 # roughly based on customers per week (1150 * 7 + 50 +50 = 8150)
  # based on customer retention stats
  chance-regular-customer-visits: 0.9
  chance-new-customer-becomes-regular: 0.035
  chance-of-losing-regular-customer: 0.0004 # 0.15 / 365

logging:
  version: 1
  formatters:
    simple:
      format: "%(name)s - %(lineno)d -  %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple
      stream: ext://sys.stdout
  loggers:
    kafka:
      level: ERROR
  root:
    level: DEBUG
    handlers: [console]
